# Generated by prelude setup.
#  Run again: `nix run github:darkmatter/prelude#setup`
#
# A flake-parts module: import it next to Prelude's module, e.g.
#
#   imports = [ prelude.flakeModules.default ./prelude.nix ];
#
# Every supported option is listed below. Values you chose in the wizard are
# active; everything else is commented at its default so you can see and
# enable options without leaving this file. Full prose reference:
# docs/reference/options.md (regenerated by docs-sync).
#
{ ... }:
{
  prelude = {
    theme = "apathy"; # color theme for all components; default "phosphor"

    # Per-token overrides on top of the theme (null keeps the theme token).
    # Values: null | hex string | ANSI-256 index.
    # palette.fg = null;
    # palette.muted = null;
    # palette.dim = null;
    # palette.border = null;
    # palette.accentBorder = null;
    # palette.accent = null;
    # palette.accent2 = null;
    # palette.success = null;
    # palette.warning = null;
    # palette.info = null;
    # palette.error = null;
    # palette.selectionFg = null;
    # palette.bg = null;
    # palette.surface = null;
    # palette.secondary = null;

    colorProfile = "auto"; # "auto" | "truecolor" | "ansi256"; default "auto"

    project = "acme"; # shown in the MOTD banner and menu header; default "devshell"

    # Project commands keyed by public `x` name. The first colon infers the
    # menu group; the complete key stays callable (e.g. `x db:migrate`).
    commands = {

      dev = {
        exec = "./scripts/develop"; # defaults to the key suffix after the first colon
        description = "Run the development server";
        # group inferred from key: develop  # first colon segment; builtins land in "prelude"
        # key = null;  # single-key accelerator (`x <key>`)
        # usage = "./scripts/develop";  # usage form shown in menu details
        # details = null;  # extended description before arg entry
        # examples = [ "./scripts/develop" ];  # worked example invocations
        # args = [ ];  # arg-entry mode: { token, description?, required?, boolean?, options? }
        # invocation = null;  # canonical shell text for duplicate detection; defaults to exec
        motd = 100; # MOTD Getting Started sort order; null hides from MOTD
      };

      test = {
        exec = "bun run test"; # defaults to the key suffix after the first colon
        description = "Run all tests";
        motd = 200; # MOTD Getting Started sort order; null hides from MOTD
      };

      typecheck = {
        exec = "bun run typecheck"; # defaults to the key suffix after the first colon
        description = "Type-check the project";
      };

      fmt = {
        exec = "nix run .#formatter"; # defaults to the key suffix after the first colon
        description = "Run the formatter";
        motd = 300; # MOTD Getting Started sort order; null hides from MOTD
      };

      "tls:setup" = {
        exec = "dev-tls"; # defaults to the key suffix after the first colon
        description = "Materialise the shared dev TLS certificate";
        details = "Decrypts ops/secrets/dev-tls.sops.yaml onto this machine. `dev-tls issue --save` mints a new one and shares it.";
        motd = 150; # MOTD Getting Started sort order; null hides from MOTD
      };

      "tls:init-sops" = {
        exec = "sops-init"; # defaults to the key suffix after the first colon
        description = "Fetch the default .sops.yaml from gist.dm.sh";
        details = "One-time, for a new project. Grants the shared KMS dev key and the tailnet key service so nobody is locked out.";
      };

      lint = {
        exec = "nix run .#lint"; # defaults to the key suffix after the first colon
        description = "Run the linter";
      };

      ci = {
        exec = "nix build"; # defaults to the key suffix after the first colon
        description = "Run CI Build";
      };

      check = {
        exec = "nix flake check"; # defaults to the key suffix after the first colon
        description = "Run checks";
      };
    };

    # Static devshell welcome banner.
    motd = {
      enable = true;

      title = {
        text = ./title.txt; # multiline title file; null uses the project-name wordmark
        align = "center"; # left|center|right; default "left"
        # style = "spine";  # wordmark when text is null: plain|spine|bracketed|label|inline|inverted
      };

      # background = null;  # block fill: null/false | true (theme bg) | color | { relative } | { blend }
      # windowBackground = null;  # full-width window fill; same value forms as background
      # clearScreen = true;  # clear the terminal before rendering
      # align = "center";  # horizontal placement of the MOTD block: left|center|right
      # width = "full";  # content width or "full"
      # maxWidth = 96;  # maximum content width
      # fullscreen = false;  # fill terminal width with no cap (width=full + maxWidth=null)

      # Outer spacing: top/bottom blank lines, left/right columns (sides supersede x/y).
      # margin = {
      #   x = 0;           # horizontal shorthand
      #   y = 0;           # vertical shorthand
      #   top = 10;        # supersedes y
      #   bottom = null;   # supersedes y
      #   left = null;     # supersedes x
      #   right = null;    # supersedes x
      #   minHeight = 0;   # apply vertical sides only at/above this terminal height
      # };

      # Inner spacing between content and block edge (sides supersede x/y).
      # padding = {
      #   x = 0;
      #   y = 0;
      #   top = null;
      #   bottom = null;
      #   left = null;
      #   right = null;
      #   minHeight = 0;
      # };

      # Hero bar: tagline, status lights, activation copy.
      # header = {
      #   tagline = {
      #     text = "Dev Shell Activated";
      #     subtitle = "Your environment is ready";
      #     layout = "stack";  # "stack" | "inline"
      #     align = "left";  # "left" | "center"
      #   };
      #   background = true;  # true = raised bar; null/false = transparent; color | { relative }
      #   statusHint = {
      #     layout = "below";  # "below" | "inline"
      #     links = [ ];  # terminal hyperlinks after the reload hint: { label, url }
      #   };
      #   # Keyed lights, sorted by order then name. Static: { status }. Live: { check, … }.
      #   status = {
      #     ready = { status = "ready"; };
      #     # nix = {
      #     #   order = 100;
      #     #   label = "nix";
      #     #   check = "nix --version >/dev/null";
      #     #   async = true;  # background refresh
      #     #   ok = "ok";
      #     #   fail = "fail";
      #     #   failLevel = "error";  # "error" | "warning"
      #     #   output = "";  # "" | "light" | "diagnostic"
      #     # };
      #   };
      # };

      # Styled text under the header; empty text hides it.
      # description = {
      #   text = "";
      #   foreground = null;  # null uses the theme role color
      #   background = null;  # null/false | true | color | { relative }
      #   bold = false;
      #   italic = false;
      #   faint = false;
      #   tips = [ ];  # optional tip lines; wrap commands in backticks
      # };

      # links = [ ];  # terminal hyperlinks under the description: { label, url }
      # env = [  # info chips; each sets exactly one of value (static) or probe (command)
      #   # { label = "node"; value = "22.3.0"; }
      #   # { label = "nix"; probe = "nix --version | awk '{print $NF}'"; }
      # ];
      # recipes = {  # multi-step workflows keyed by name
      #   # clean-local-stack = {
      #   #   order = 1000;
      #   #   title = "spin up a clean local stack";
      #   #   steps = [
      #   #     { comment = "start postgres first"; }
      #   #     { command = "just db:up"; }
      #   #   ];
      #   # };
      # };

      # Labels for the commands + examples region.
      # gettingStarted = {
      #   heading = "Getting Started";
      #   commandsLabel = "commands";
      #   examplesLabel = "examples";
      # };
    };

    # Interactive command picker (bubbletea TUI).
    menu = {
      enable = true;
      # placeholder = "type to filter commands…";  # filter input hint
      # height = 12;  # filter list height in rows
      # execute = true;  # false prints the selected command instead of running it
      # width = "full";  # content width or "full"
      # maxWidth = 96;
    };

    # Themed starship config (`packages.prompt` = starship.toml).
    prompt = {
      enable = true;
      # settings = { };  # merged over themed defaults; see https://starship.rs/config/
      #   # add_newline = true;
      #   # format = "$directory$git_branch$character";
      # configFile = null;  # use this starship.toml verbatim instead of generating one
    };

    # Markdown pages in the navigable docs viewer. Each file becomes one
    # CONTENTS sidebar entry; digits 1–9 jump between pages. The first
    # level-one heading labels the entry.
    # docs.pages = [
    #   { text = ./docs/getting-started.md; }
    #   # Or split one file into H2 leaves (bind the flake's lib):
    #   # (inputs.prelude.lib.mdSplit ./README.md)
    # ];
    docs.pages = [ ];

    # Preferred command-group order. Groups omitted follow alphabetically;
    # the built-in "prelude" group (menu/docs) stays first.
    # sort.groups = [ "develop" ];
  };
}
