apiVersion: v1
kind: Secret
metadata:
    name: ops-demo-example
stringData:
    DEMO_MESSAGE: ENC[AES256_GCM,data:XS2kjpMAp1TVT2ATulNuNXx/+t7w3JZkxTMVWDP0Yw==,iv:nn6zTg8ZRLQZePr9kplX1oq2rVNYtd8bgsUT2QJfvdA=,tag:wTCiQ2m1UfdD5cuhLlKLhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeHV1bEViOUpTQ2NwaXFT
            OUxUbHErU242SHFCQlVvTmRrSlpXN0djc0JnCjNLMzhPVUliV3d5UGt5YXVuclA1
            NFhrYnAwZmVmcXIrSmtxK29Pc0h3R00KLS0tIDgvQlpSbVpyVDlsQVF4ZTR0ZEkv
            NlRKQUF2dFVFSFhPSksyMktYRVMwTTQKYMQRduebXofuetMJwbfifncHKVqrkUW0
            wvWuoVbdTVlA0PDFAAXe/28H4caV0TSVbjrsz/Gh4l/pEAdD5Q5CPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g3cu6tk8q8as2przsqhur3u3anss9rh2splyvqy5fhsa9d53qezs8zvxng
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T22:16:29Z"
    mac: ENC[AES256_GCM,data:TOFC/vkW0wfD+gW+HhPd5UtQo/pD6ISad3UoOrrh9bAJGZZGGFWr8v5TW2eU3r2GTHd/e5BQQO31VnxpNRkljNaD0avbvTYtG1mUgXZS/Gb1LoLFW49Q18oQ6+W+AYWRyeYuKFcPBheIC8fLEawmEfQkxBG51MMm0sAAsGGNFUk=,iv:icl50lDw9GW5dv/sOmKO9cLPM6OK2XKk2DC+q2VMRZw=,tag:Ezb1xUY3d/l1dq7ZHfOObA==,type:str]
    version: 3.13.3
