keys:
  - &github_actions age1eqcj2g0fdekj2wpqp4y0fg9c5myydjdt9zlr5scr0grk6fxszymqkpw5jf
  # keyservice runs on our internal network, and allows us to decrypt so long as
  # we are connected to tailscale.
  - &keyservice age16wuzuxnkcgfuxzvzgk5e5a5f6hhs386adjewyv54m9esr4yj6uuslpn6tp
  - &cooper age1vapyvpjzqg8wdfay055s574qt0u6avtzv4ch7kv0epvtycpyjqzqk3m4yr
creation_rules:
  - path_regex: .*
    unencrypted_comment_regex: .*\bsafe$
    age:
      - *github_actions
      - *keyservice
      - *cooper
