apiVersion: v1
kind: Service
metadata:
  name: ops-demo-web
  labels:
    app.kubernetes.io/name: ops-demo
spec:
  selector:
    app.kubernetes.io/name: ops-demo
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
