apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: template-production
resources:
  - ../../deploy/kubernetes/base
  - ../../deploy/kubernetes/database
generators:
  - postgres-secret-generator.yaml
patches:
  - path: ghcr-pull-secret.patch.yaml
  - path: replicas.patch.yaml
  - path: runtime-config.patch.yaml
  - path: resources.patch.yaml
images:
  - name: ghcr.io/example/agent-demo
    newName: ghcr.io/darkmatter/template
    digest: sha256:c895e5dd9c30feb83ebd24c93d068a9eb4864691fab95bd26c2ded5d01b208d8
