apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: template-production
resources:
  - ../../deploy/kubernetes/base
  - ../../deploy/kubernetes/database
generators:
  - postgres-secret-generator.yaml
patches:
  - path: ghcr-pull-secret.patch.yaml
  - path: replicas.patch.yaml
  - path: runtime-config.patch.yaml
  - path: resources.patch.yaml
images:
  - name: ghcr.io/example/agent-demo
    newName: ghcr.io/darkmatter/template
    digest: sha256:7985fb45e2c0abd4cd3e829e59a2f722773baa0d1a1293d44af7e3d00bde597a
